//! Turning the measurements into `PARITY.md`.
//!
//! The document is generated and committed, and CI regenerates it and fails
//! on a diff — the same arrangement as the golden fixtures, and for the same
//! reason: a score that only exists in a CI log is a score nobody reads, and
//! a score that can change without a diff is a score nobody can trust.

use std::collections::BTreeSet;
use std::fmt::Write as _;

use crate::roundtrip::RoundTrip;
use crate::{Outcome, Source, Targets, Verdict};

pub struct Summary<'a> {
    pub outcomes: &'a [Outcome],
    pub targets: &'a Targets,
    pub trips: &'a [RoundTrip],
}

pub struct Counts {
    pub settled: usize,
    pub matched: usize,
    pub open: usize,
    /// Differences the corpus already records. Counted as misses, so the rate
    /// tells the truth, but they do not fail the build.
    pub accepted: usize,
}

impl Summary<'_> {
    pub fn counts(&self) -> Counts {
        Counts {
            settled: self
                .outcomes
                .iter()
                .filter(|o| o.case.source.settled())
                .count(),
            matched: self
                .outcomes
                .iter()
                .filter(|o| o.verdict == Verdict::Match)
                .count(),
            open: self
                .outcomes
                .iter()
                .filter(|o| !o.case.source.settled())
                .count(),
            accepted: self
                .outcomes
                .iter()
                .filter(|o| matches!(o.verdict, Verdict::Accepted { .. }))
                .count(),
        }
    }

    /// Functions named by at least one case.
    fn pinned(&self) -> BTreeSet<&str> {
        self.outcomes
            .iter()
            .flat_map(|o| o.case.functions.iter())
            .map(|s| s.as_str())
            .collect()
    }

    /// Whether every settled case passes and every fixture round-trips. The
    /// exit code CI reads.
    pub fn ok(&self) -> bool {
        !self.outcomes.iter().any(|o| o.verdict.fails()) && self.trips.iter().all(|t| t.clean())
    }
}

fn percent(part: usize, whole: usize) -> String {
    if whole == 0 {
        return "n/a".into();
    }
    format!("{:.1}%", 100.0 * part as f64 / whole as f64)
}

pub fn render(s: &Summary) -> String {
    let mut out = String::new();
    let counts = s.counts();
    let pinned = s.pinned();

    let tier1_done = s
        .targets
        .tier1
        .iter()
        .filter(|f| crate::implemented(f))
        .count();
    let tier2_done = s
        .targets
        .tier2
        .iter()
        .filter(|f| crate::implemented(f))
        .count();
    let target_total = s.targets.tier1.len() + s.targets.tier2.len();
    let target_done = tier1_done + tier2_done;
    let pinned_done = s
        .targets
        .all()
        .filter(|f| crate::implemented(f) && pinned.contains(f.as_str()))
        .count();

    out.push_str(
        "# Excel parity\n\n\
         Generated by `gridline-parity report`. Do not edit by hand — CI regenerates\n\
         this file and fails if the result differs from what is committed.\n\n",
    );

    out.push_str(
        "> **Where these expectations come from.** Microsoft Excel does not run on the\n\
         > machines this project is developed on, and no expectation in the corpus was\n\
         > recorded by running it. Each case cites its source: `known` for documented or\n\
         > universally reproduced Excel behaviour, `spec` for a citation to ECMA-376 or\n\
         > MS-OI29500, and `open` for behaviour nobody here can settle. **Only `known`\n\
         > and `spec` cases count toward the match rate.** Open questions are listed at\n\
         > the bottom with every candidate answer, including ours.\n\n",
    );

    out.push_str("## Scorecard\n\n");
    out.push_str("| Measure | Score | |\n| --- | --- | --- |\n");
    let _ = writeln!(
        out,
        "| Cell match (settled cases) | **{}** | {} of {} |",
        percent(counts.matched, counts.settled),
        counts.matched,
        counts.settled
    );
    let _ = writeln!(
        out,
        "| Function coverage | **{}** | {} of {} target functions implemented |",
        percent(target_done, target_total),
        target_done,
        target_total
    );
    let _ = writeln!(
        out,
        "| Functions pinned by a case | **{}** | {} of {} implemented |",
        percent(pinned_done, target_done),
        pinned_done,
        target_done
    );
    let clean_trips = s.trips.iter().filter(|t| t.clean()).count();
    let _ = writeln!(
        out,
        "| Round-trip fidelity | **{}** | {} of {} workbooks |",
        percent(clean_trips, s.trips.len()),
        clean_trips,
        s.trips.len()
    );
    let _ = writeln!(
        out,
        "| Recorded differences | {} | counted as misses above |",
        counts.accepted
    );
    let _ = writeln!(out, "| Open questions | {} | excluded above |", counts.open);
    out.push('\n');

    // --- Functions ---------------------------------------------------------
    out.push_str("## Functions\n\n");
    let _ = writeln!(
        out,
        "Tier 1 is the v1 scope; tier 2 is the next set worth having, listed so this\n\
         number measures something. A function is *pinned* when at least one corpus\n\
         case names it — implemented and unpinned means the behaviour is untested\n\
         against anything but our own opinion.\n"
    );
    for (label, list) in [("Tier 1", &s.targets.tier1), ("Tier 2", &s.targets.tier2)] {
        let done = list.iter().filter(|f| crate::implemented(f)).count();
        let _ = writeln!(
            out,
            "\n### {label} — {} of {} implemented\n",
            done,
            list.len()
        );
        out.push_str("| Function | Implemented | Pinned |\n| --- | --- | --- |\n");
        for f in list {
            let have = crate::implemented(f);
            let _ = writeln!(
                out,
                "| `{f}` | {} | {} |",
                if have { "yes" } else { "—" },
                if pinned.contains(f.as_str()) {
                    "yes"
                } else {
                    "—"
                }
            );
        }
    }
    out.push('\n');

    // --- Differences -------------------------------------------------------
    let differing: Vec<&Outcome> = s
        .outcomes
        .iter()
        .filter(|o| {
            matches!(
                o.verdict,
                Verdict::Differs { .. } | Verdict::Accepted { .. }
            )
        })
        .collect();
    out.push_str("## Known differences\n\n");
    if differing.is_empty() {
        out.push_str("None: every settled case in the corpus matches.\n\n");
    } else {
        out.push_str(
            "| Case | Formula | Excel | Gridline | Recorded |\n| --- | --- | --- | --- | --- |\n",
        );
        for o in &differing {
            let (got, recorded) = match &o.verdict {
                Verdict::Differs { got } => (got, "**new**"),
                Verdict::Accepted { got } => (got, "yes"),
                _ => continue,
            };
            let _ = writeln!(
                out,
                "| `{}` | `{}` | `{}` | `{}` | {} |",
                o.case.id,
                escape(&o.case.formula),
                escape(&o.case.expect),
                escape(got),
                recorded
            );
        }
        out.push_str(
            "\nA row marked **new** is a regression and fails the build. A recorded one is a\n             difference we know about and have not fixed; it lowers the score above, and\n             the build fails if it starts matching without the corpus being updated.\n\n",
        );
    }

    // --- Round trip --------------------------------------------------------
    out.push_str("## Round trip\n\n");
    out.push_str(
        "Every workbook in `fixtures/` is opened, saved, and opened again. *State* is\n\
         the recalculated workbook; *preserved* counts the zip entries that came back\n\
         byte-identical. Only the worksheet XML and the style sheet are regenerated,\n\
         so anything else in the rewritten column would be a defect.\n\n",
    );
    out.push_str(
        "| Workbook | State | Preserved | Rewritten | Lost |\n| --- | --- | --- | --- | --- |\n",
    );
    for t in s.trips {
        let _ = writeln!(
            out,
            "| `{}` | {} | {} | {} | {} |",
            t.file,
            match (&t.error, t.state_identical) {
                (Some(e), _) => format!("error: {e}"),
                (None, true) => "identical".into(),
                (None, false) => "**changed**".into(),
            },
            t.preserved,
            t.rewritten.len(),
            t.lost.len()
        );
    }
    out.push('\n');

    // --- Open questions ----------------------------------------------------
    let open: Vec<&Outcome> = s
        .outcomes
        .iter()
        .filter(|o| o.case.source == Source::Open)
        .collect();
    out.push_str("## Open questions\n\n");
    if open.is_empty() {
        out.push_str("None recorded.\n");
    } else {
        out.push_str(
            "Behaviour nobody here can settle without Excel in front of them. Each one\n\
             records what Gridline currently does, so resolving it later is a matter of\n\
             changing a corpus entry and seeing what fails.\n\n",
        );
        for o in open {
            let got = match &o.verdict {
                Verdict::Unsettled { got } => got.clone(),
                _ => String::new(),
            };
            let _ = writeln!(out, "### `{}`\n", o.case.id);
            let _ = writeln!(out, "```\n{}\n```\n", o.case.formula);
            let _ = writeln!(out, "{}\n", o.case.note.trim());
            if !o.case.candidates.is_empty() {
                let _ = writeln!(out, "Candidates: {}\n", o.case.candidates.join(", "));
            }
            let _ = writeln!(out, "Gridline currently answers `{}`.\n", escape(&got));
        }
    }

    out
}

/// Keep a value from breaking the table it sits in.
fn escape(s: &str) -> String {
    s.replace('|', "\\|").replace('\n', " ")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::Case;
    use std::collections::BTreeMap;

    fn case(id: &str, source: Source) -> Case {
        Case {
            id: id.into(),
            given: BTreeMap::new(),
            formula: "=1+1".into(),
            at: "Z1".into(),
            expect: "2".into(),
            source,
            note: "n".into(),
            candidates: Vec::new(),
            known_difference: false,
            functions: vec!["SUM".into()],
        }
    }

    fn targets() -> Targets {
        Targets {
            tier1: vec!["SUM".into(), "IF".into()],
            tier2: vec!["SUMPRODUCT".into()],
        }
    }

    #[test]
    fn an_open_case_is_in_neither_the_numerator_nor_the_denominator() {
        let outcomes = vec![
            Outcome {
                case: case("a", Source::Known),
                verdict: Verdict::Match,
            },
            Outcome {
                case: case("b", Source::Open),
                verdict: Verdict::Unsettled { got: "2".into() },
            },
        ];
        let t = targets();
        let s = Summary {
            outcomes: &outcomes,
            targets: &t,
            trips: &[],
        };
        let c = s.counts();
        assert_eq!((c.settled, c.matched, c.open), (1, 1, 1));
        assert!(s.ok(), "an unsettled case must not fail the run");
        assert!(render(&s).contains("1 of 1"));
    }

    #[test]
    fn a_difference_fails_the_run_and_is_named_in_the_report() {
        let outcomes = vec![Outcome {
            case: case("op.thing", Source::Known),
            verdict: Verdict::Differs { got: "3".into() },
        }];
        let t = targets();
        let s = Summary {
            outcomes: &outcomes,
            targets: &t,
            trips: &[],
        };
        assert!(!s.ok());
        let text = render(&s);
        assert!(text.contains("op.thing"), "{text}");
        assert!(text.contains("| `2` | `3` |"), "{text}");
    }

    #[test]
    fn coverage_counts_what_is_missing_not_only_what_is_there() {
        // A target list naming only what is built would report 100% forever.
        let t = targets();
        let s = Summary {
            outcomes: &[],
            targets: &t,
            trips: &[],
        };
        let text = render(&s);
        assert!(text.contains("2 of 3 target functions"), "{text}");
        assert!(text.contains("| `SUMPRODUCT` | — |"), "{text}");
    }

    #[test]
    fn a_lost_part_fails_the_run() {
        let t = targets();
        let trips = vec![RoundTrip {
            file: "x.xlsx".into(),
            preserved: 3,
            rewritten: vec![],
            lost: vec!["xl/theme/theme1.xml".into()],
            state_identical: true,
            error: None,
        }];
        let s = Summary {
            outcomes: &[],
            targets: &t,
            trips: &trips,
        };
        assert!(
            !s.ok(),
            "losing a part someone else's software needs is a failure"
        );
    }
}
