#!/usr/bin/env bash
#
# The demonstration, end to end.
#
# Everything here is reproducible from an empty directory: seed a database with
# a workbook's worth of scripted history, mine it, export the dataset, and
# print what to do in the browser. Nothing is faked — the events are built by
# the same redaction the client calls, the routines by the same miner, and the
# consent refusal by the same query the export uses.
#
#   scripts/demo.sh              # build, seed, mine, export
#   scripts/demo.sh --keep       # leave an existing database alone
#
set -euo pipefail

cd "$(dirname "$0")/.."
OUT=${GRIDLINE_DEMO_DIR:-demo}
DB="$OUT/gridline.db"
KEEP=0
[[ "${1:-}" == "--keep" ]] && KEEP=1

say() { printf '\n\033[1m== %s\033[0m\n' "$1"; }

say "Building"
cargo build --workspace --quiet

# The workbook is generated by the golden tests rather than committed as a
# binary, so a clean checkout has to run them once.
if [[ ! -f fixtures/demo-dues-ledger.xlsx ]]; then
  say "Generating the demo workbook"
  UPDATE_GOLDEN=1 cargo test -p engine --test golden_workbooks --quiet
fi

mkdir -p "$OUT"
if [[ $KEEP -eq 0 ]]; then
  rm -f "$DB"
fi

say "Seeding the scripted history"
./target/debug/seed_demo --db "sqlite://$DB?mode=rwc" \
  --log "$OUT/events.jsonl" --workbook "$OUT/dues-ledger.xlsx"

say "Mining"
# Nothing runs the miner on a schedule yet; the demo runs it here, which is
# also what a nightly cron would do.
./target/debug/gridline-miner mine --in "$OUT/events.jsonl" --db "$DB"

say "Exporting the demonstration dataset"
./target/debug/gridline-miner export \
  --consented-only --mode structural --db "$DB" --out "$OUT/data"

say "What was produced"
echo "  database:  $DB"
echo "  workbook:  $OUT/dues-ledger.xlsx  (the fixture with the scripted work in it)"
echo "  event log: $OUT/events.jsonl"
echo "  dataset:   $OUT/data  ($(ls "$OUT"/data/*.jsonl | wc -l | tr -d ' ') session files + manifest)"
echo
echo "The second actor in the seed declined capture. Their events are in the"
echo "database and none of them are in the dataset — grep it for 'no-s_demo'"
echo "and you should find nothing:"
if grep -q "no-s_demo" "$OUT"/data/*.jsonl 2>/dev/null; then
  echo "  FAILED: an actor who declined was exported" >&2
  exit 1
fi
echo "  confirmed: 0 matches"

cat <<'NEXT'

== Now in the browser

  DATABASE_URL="sqlite://demo/gridline.db?mode=rwc" make dev

  1. Open demo/dues-ledger.xlsx — the fixture with the scripted history
     already in it, so the workbook and the event log agree about what
     happened. Styles, the theme and the shared string table are the file's
     own, preserved through the round trip.
  2. Sign in with the token printed above, and choose "structural" capture.
     The chip in the header says when recording is on; pause it and it stops.
  3. Open the Routines panel. The mined habit is there: enter a member row,
     repeated twelve times across three sittings. It names the four values it
     cannot fill, because the log only ever held their hashes.
  4. Type a name, tier, joined date and amount into A19:D19 — the four values
     the routine says it cannot fill. Select A19 and press Preview: the diff
     is computed by the same engine the run will use, and it shows the six
     formulas it would write. Press Run; one undo step reverses all of it.
  5. Add a sheet, rename one, save the workbook, and reopen it. The parts
     Gridline does not model come back untouched.
  6. Visit /transparency for the action vocabulary, then revoke consent and
     re-run the export above: the dataset comes back empty.
NEXT
