//! Golden workbook tests: every fixture in `fixtures/` imports, recalculates,
//! and must match its stored snapshot of computed values.
//!
//! The fixtures are generated by this file rather than committed as binaries,
//! so the inputs stay reviewable in the diff. Run with `UPDATE_GOLDEN=1` to
//! rewrite the snapshots after an intentional behavior change — and read the
//! diff before committing it, because a snapshot that changes silently is the
//! whole failure mode these tests exist to catch.

use engine::io::xlsx;
use engine::{Action, BorderPreset, CellAddr, CellFormat, Engine, FormatPatch, HAlign, RangeAddr};
use std::path::PathBuf;

fn fixtures_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .unwrap()
        .parent()
        .unwrap()
        .join("fixtures")
}

fn set(e: &mut Engine, sheet: &str, a1: &str, input: &str) {
    e.apply(&Action::CellEdit {
        sheet: sheet.into(),
        addr: CellAddr::parse_a1(a1).unwrap(),
        input: input.into(),
    })
    .unwrap();
}

fn fmt(e: &mut Engine, sheet: &str, range: &str, patches: Vec<FormatPatch>) {
    e.apply(&Action::FormatApply {
        sheet: sheet.into(),
        range: RangeAddr::parse_a1(range).unwrap(),
        patches,
    })
    .unwrap();
}

/// The resolved format at an address.
fn format_at(e: &Engine, sheet: &str, a1: &str) -> CellFormat {
    let s = e.wb.sheet_by_name(sheet).expect("sheet exists");
    e.wb.formats
        .resolve(s.format_id(CellAddr::parse_a1(a1).unwrap()))
}

/// A dues ledger exercising the function families a real back-office sheet
/// leans on: lookup, conditional aggregation, text, and dates.
fn dues_ledger() -> Engine {
    let mut e = Engine::new();
    e.now_ms = 1_704_110_400_000; // 2024-01-01T12:00:00Z, so TODAY() is stable

    e.apply(&Action::SheetRename {
        from: "Sheet1".into(),
        to: "Ledger".into(),
    })
    .unwrap();
    e.apply(&Action::SheetAdd {
        name: "Rates".into(),
    })
    .unwrap();

    // Rate card: membership tier -> annual dues.
    for (i, (tier, rate)) in [("basic", "120"), ("plus", "300"), ("pro", "750")]
        .iter()
        .enumerate()
    {
        let r = i + 1;
        set(&mut e, "Rates", &format!("A{r}"), tier);
        set(&mut e, "Rates", &format!("B{r}"), rate);
    }

    // Every column the sheet uses is labelled. Six unlabelled columns under a
    // header band is what an unfinished sheet looks like, and this one is the
    // demo's front page.
    let headers = [
        "member",
        "tier",
        "joined",
        "paid",
        "owed",
        "balance",
        "status",
        "label",
        "year",
        "owed (fmt)",
    ];
    for (c, h) in headers.iter().enumerate() {
        set(
            &mut e,
            "Ledger",
            &format!("{}1", (b'A' + c as u8) as char),
            h,
        );
    }
    let rows = [
        ("Ada", "pro", "2021-03-15", "750"),
        ("Grace", "basic", "2022-07-01", "0"),
        ("Alan", "plus", "2020-11-30", "150"),
        ("Katherine", "pro", "2023-01-09", "750"),
        ("Edsger", "basic", "2019-05-22", "120"),
    ];
    for (i, (name, tier, joined, paid)) in rows.iter().enumerate() {
        let r = i + 2;
        set(&mut e, "Ledger", &format!("A{r}"), name);
        set(&mut e, "Ledger", &format!("B{r}"), tier);
        set(&mut e, "Ledger", &format!("C{r}"), joined);
        set(&mut e, "Ledger", &format!("D{r}"), paid);
        // Owed, balance, status, and a display label.
        set(
            &mut e,
            "Ledger",
            &format!("E{r}"),
            // The rate card does not move, so the reference to it is absolute:
            // a relative one silently walks off the table when the row is
            // filled down, which is a bug waiting in a real ledger.
            &format!("=VLOOKUP(B{r},Rates!$A$1:$B$3,2,FALSE)"),
        );
        set(&mut e, "Ledger", &format!("F{r}"), &format!("=E{r}-D{r}"));
        set(
            &mut e,
            "Ledger",
            &format!("G{r}"),
            &format!("=IF(F{r}<=0,\"settled\",IF(F{r}>=E{r},\"unpaid\",\"partial\"))"),
        );
        set(
            &mut e,
            "Ledger",
            &format!("H{r}"),
            &format!("=PROPER(A{r})&\" (\"&UPPER(B{r})&\")\""),
        );
        // DATEVALUE is not in the v1 set, so pull the year out of the ISO
        // text — what a user without it would do.
        set(
            &mut e,
            "Ledger",
            &format!("I{r}"),
            &format!("=VALUE(LEFT(C{r},4))"),
        );
        set(
            &mut e,
            "Ledger",
            &format!("J{r}"),
            &format!("=TEXT(E{r},\"$#,##0.00\")"),
        );
    }

    // Summary block, well below the member table and reading a range with
    // room in it: a ledger someone actually keeps grows, and a total that
    // stops at the fifth row is a total that quietly goes wrong on the sixth.
    set(&mut e, "Ledger", "A22", "total owed");
    set(&mut e, "Ledger", "B22", "=SUM(E2:E20)");
    set(&mut e, "Ledger", "A23", "total outstanding");
    set(&mut e, "Ledger", "B23", "=SUM(F2:F20)");
    set(&mut e, "Ledger", "A24", "unpaid count");
    set(&mut e, "Ledger", "B24", "=COUNTIF(G2:G20,\"unpaid\")");
    set(&mut e, "Ledger", "A25", "pro dues");
    set(&mut e, "Ledger", "B25", "=SUMIF(B2:B20,\"pro\",E2:E20)");
    set(&mut e, "Ledger", "A26", "average owed");
    set(&mut e, "Ledger", "B26", "=AVERAGE(E2:E20)");
    set(&mut e, "Ledger", "A27", "members joined before 2022");
    set(&mut e, "Ledger", "B27", "=COUNTIF(I2:I20,\"<2022\")");
    set(&mut e, "Ledger", "A28", "longest name");
    set(
        &mut e,
        "Ledger",
        "B28",
        "=MAX(LEN(A2),LEN(A3),LEN(A4),LEN(A5),LEN(A6))",
    );
    // A deliberate error, so the snapshot pins error rendering too.
    set(&mut e, "Ledger", "A29", "missing tier");
    set(
        &mut e,
        "Ledger",
        "B29",
        "=VLOOKUP(\"gold\",Rates!$A$1:$B$3,2,FALSE)",
    );

    // Dress it the way someone actually would, so the round trip has real
    // formatting to lose: a header band, currency columns, a boxed summary,
    // and a red flag on the error row.
    fmt(
        &mut e,
        "Ledger",
        "A1:J1",
        vec![
            FormatPatch::Bold(true),
            FormatPatch::FillColor(Some("#dbeae1".into())),
            FormatPatch::Align(Some(HAlign::Center)),
            FormatPatch::Border(BorderPreset::All),
        ],
    );
    // The currency band covers the rows the table will grow into, not just
    // the ones already filled: a format that stops at the last row makes the
    // next row someone types look like a different sheet.
    fmt(
        &mut e,
        "Ledger",
        "D2:F20",
        vec![FormatPatch::NumberFormat(Some("$#,##0.00".into()))],
    );
    fmt(
        &mut e,
        "Ledger",
        "A22:B29",
        vec![FormatPatch::Border(BorderPreset::Outline)],
    );
    fmt(
        &mut e,
        "Ledger",
        "A29:B29",
        vec![
            FormatPatch::FontColor(Some("#b3261e".into())),
            FormatPatch::Italic(true),
        ],
    );
    // A format with no cell under it: the column heading for a field nobody
    // has filled in yet.
    fmt(
        &mut e,
        "Ledger",
        "K1:K6",
        vec![FormatPatch::FillColor(Some("#f5f5f5".into()))],
    );
    fmt(&mut e, "Rates", "A1:B3", vec![FormatPatch::Bold(true)]);

    e
}

/// A formula torture sheet: precedence, coercion, and error propagation.
fn formula_torture() -> Engine {
    let mut e = Engine::new();
    e.now_ms = 1_704_110_400_000;
    let cases = [
        ("A1", "=1+2*3"),
        ("A2", "=(1+2)*3"),
        ("A3", "=2^3^2"),
        ("A4", "=-2^2"),
        ("A5", "=50%*10"),
        ("A6", "=\"a\"&1.5"),
        ("A7", "=1/0"),
        ("A8", "=A7+1"),
        ("A9", "=IFERROR(A7,\"caught\")"),
        ("A10", "=TRUE+1"),
        ("A11", "=\"3\"+4"),
        ("A12", "=Z99+5"),
        ("A13", "=\"x\"&Z99"),
        ("A14", "=0^0"),
        ("A15", "=MOD(-3,2)"),
        ("A16", "=ROUND(2.675,2)"),
        ("A17", "=INT(-1.5)"),
        ("A18", "=SQRT(-1)"),
        ("A19", "=NOSUCHFUNC(1)"),
        ("A20", "=99999<\"a\""),
        ("B1", "=SUM(A1:A6)"),
        ("B2", "=COUNT(A1:A20)"),
        ("B3", "=COUNTA(A1:A20)"),
        ("B4", "=TEXTJOIN(\"|\",TRUE,A1:A5)"),
        ("B5", "=DATE(2024,2,29)"),
        ("B6", "=WEEKDAY(DATE(2024,1,1),2)"),
        ("B7", "=EOMONTH(DATE(2024,1,31),1)"),
        ("B8", "=DATEDIF(DATE(2020,1,1),DATE(2024,3,1),\"M\")"),
    ];
    for (a1, input) in cases {
        set(&mut e, "Sheet1", a1, input);
    }
    e
}

fn check_golden(name: &str, build: fn() -> Engine) {
    let dir = fixtures_dir();
    std::fs::create_dir_all(&dir).expect("create fixtures dir");
    let xlsx_path = dir.join(format!("{name}.xlsx"));
    let snapshot_path = dir.join(format!("{name}.expected.json"));

    let built = build();
    let bytes = xlsx::export(&built.wb).expect("export fixture");
    // The binary is only rewritten on demand: xlsx embeds timestamps, so
    // writing it every run would leave the working tree permanently dirty.
    // The assertions below run against freshly generated bytes regardless,
    // so the committed fixture can never drift from its generator unnoticed.
    let refresh = std::env::var("UPDATE_GOLDEN").is_ok() || !xlsx_path.exists();
    if refresh {
        std::fs::write(&xlsx_path, &bytes).expect("write fixture");
    }

    // The real assertion: importing the file back and recalculating from
    // scratch must reproduce the same computed values.
    let imported = xlsx::import(&bytes).expect("import fixture");
    assert!(
        imported.warnings.is_empty(),
        "{name}: unexpected import warnings: {:?}",
        imported.warnings
    );
    let mut engine = imported.engine;
    engine.now_ms = built.now_ms;
    engine.recalc_all();

    let actual = engine.wb.state_snapshot();
    let pretty = serde_json::to_string_pretty(&actual).unwrap();

    if std::env::var("UPDATE_GOLDEN").is_ok() || !snapshot_path.exists() {
        std::fs::write(&snapshot_path, format!("{pretty}\n")).expect("write snapshot");
        return;
    }

    let expected: serde_json::Value =
        serde_json::from_str(&std::fs::read_to_string(&snapshot_path).expect("read snapshot"))
            .expect("parse snapshot");
    assert_eq!(
        actual, expected,
        "{name}: computed values drifted from the golden snapshot.\n\
         If this change is intentional, rerun with UPDATE_GOLDEN=1 and review the diff."
    );
}

#[test]
fn golden_dues_ledger() {
    check_golden("demo-dues-ledger", dues_ledger);
}

#[test]
fn golden_formula_torture() {
    check_golden("formula-torture", formula_torture);
}

/// Importing a fixture and exporting it again must not change the computed
/// state — the round trip is lossless for everything we model.
#[test]
fn golden_fixtures_round_trip_losslessly() {
    for (name, build) in [
        ("demo-dues-ledger", dues_ledger as fn() -> Engine),
        ("formula-torture", formula_torture as fn() -> Engine),
    ] {
        let built = build();
        let once = xlsx::export(&built.wb).expect("export");
        let mut reimported = xlsx::import(&once).expect("import").engine;
        reimported.now_ms = built.now_ms;
        reimported.recalc_all();
        let twice = xlsx::export(&reimported.wb).expect("re-export");
        let mut again = xlsx::import(&twice).expect("re-import").engine;
        again.now_ms = built.now_ms;
        again.recalc_all();
        assert_eq!(
            reimported.wb.state_snapshot(),
            again.wb.state_snapshot(),
            "{name}: state changed on the second round trip"
        );
    }
}

/// Formatting must survive the trip through xlsx, not merely exist in memory.
#[test]
fn formatting_survives_a_round_trip() {
    let built = dues_ledger();
    let bytes = xlsx::export(&built.wb).expect("export");
    let back = xlsx::import(&bytes).expect("import").engine;

    let header = format_at(&back, "Ledger", "A1");
    assert!(header.bold, "header lost its weight");
    assert_eq!(header.fill_color.as_deref(), Some("#dbeae1"));
    assert_eq!(header.align, Some(HAlign::Center));
    assert!(header.borders.top && header.borders.bottom);

    assert_eq!(
        format_at(&back, "Ledger", "E3").number_format.as_deref(),
        Some("$#,##0.00")
    );

    let flag = format_at(&back, "Ledger", "A29");
    assert!(flag.italic);
    assert_eq!(flag.font_color.as_deref(), Some("#b3261e"));

    // The summary box: an outline puts edges only on the perimeter, and that
    // asymmetry has to survive too — a round trip that turned every cell into
    // a full box would still "have borders".
    assert!(format_at(&back, "Ledger", "A22").borders.top);
    assert!(!format_at(&back, "Ledger", "A23").borders.top);

    // A formatted cell with nothing in it must come back formatted and still
    // empty.
    assert_eq!(
        format_at(&back, "Ledger", "K3").fill_color.as_deref(),
        Some("#f5f5f5")
    );
    assert!(
        !back
            .wb
            .sheet_by_name("Ledger")
            .unwrap()
            .cells
            .contains_key(&CellAddr::parse_a1("K3").unwrap()),
        "an empty formatted cell came back holding something"
    );
}

#[test]
fn a_freshly_opened_workbook_has_nothing_to_undo() {
    // Import replays the file through `apply`, so without an explicit reset
    // the first Ctrl+Z after opening a file un-types a cell the user never
    // typed — and the second, and the third.
    let bytes = xlsx::export(&dues_ledger().wb).expect("export");
    let imported = xlsx::import(&bytes).expect("import").engine;
    assert!(!imported.can_undo());
    assert!(!imported.can_redo());
}

/// Changing one cell's formatting in an *imported* workbook must append to
/// `xl/styles.xml` rather than rewrite it, so every other cell keeps exactly
/// the formatting it arrived with — including the parts we do not model.
#[test]
fn reformatting_an_imported_workbook_leaves_the_rest_alone() {
    let bytes = xlsx::export(&dues_ledger().wb).expect("export");
    let mut engine = xlsx::import(&bytes).expect("import").engine;
    assert!(
        engine.wb.preserved.is_some(),
        "the preserved-package path is the one under test here"
    );

    let before_header = format_at(&engine, "Ledger", "A1");
    fmt(
        &mut engine,
        "Ledger",
        "A22",
        vec![FormatPatch::FillColor(Some("#ffff00".into()))],
    );

    let patched = xlsx::export(&engine.wb).expect("re-export through the preserved package");
    let back = xlsx::import(&patched).expect("re-import").engine;

    // The edit landed, keeping the outline border it already had.
    let edited = format_at(&back, "Ledger", "A22");
    assert_eq!(edited.fill_color.as_deref(), Some("#ffff00"));
    assert!(edited.borders.top, "the edit dropped the existing border");

    // Everything else is exactly as it was.
    assert_eq!(format_at(&back, "Ledger", "A1"), before_header);
    assert_eq!(
        format_at(&back, "Ledger", "E3").number_format.as_deref(),
        Some("$#,##0.00")
    );
    assert_eq!(
        format_at(&back, "Ledger", "A29").font_color.as_deref(),
        Some("#b3261e")
    );
    assert_eq!(
        format_at(&back, "Ledger", "K3").fill_color.as_deref(),
        Some("#f5f5f5")
    );
    // And the values are untouched: a style patch must not disturb the data.
    assert_eq!(
        back.wb.state_snapshot()["sheets"][0]["cells"],
        engine.wb.state_snapshot()["sheets"][0]["cells"]
    );
}

/// Saving an imported workbook without touching its formatting must not add a
/// single record to the style sheet. This is what makes "open and save" safe
/// on a file full of formatting we do not model.
#[test]
fn saving_an_untouched_import_does_not_grow_the_style_sheet() {
    let bytes = xlsx::export(&dues_ledger().wb).expect("export");
    let imported = xlsx::import(&bytes).expect("import").engine;
    let original_styles = imported
        .wb
        .preserved
        .as_ref()
        .and_then(|p| p.part("xl/styles.xml"))
        .expect("the fixture has a style sheet")
        .to_vec();

    let resaved = xlsx::export(&imported.wb).expect("re-export");
    let after = xlsx::import(&resaved).expect("re-import");
    let after_styles = after
        .engine
        .wb
        .preserved
        .as_ref()
        .and_then(|p| p.part("xl/styles.xml"))
        .expect("style sheet survived");
    assert_eq!(
        original_styles, after_styles,
        "an untouched save rewrote xl/styles.xml"
    );
}
