//! Golden workbook tests: every fixture in `fixtures/` imports, recalculates,
//! and must match its stored snapshot of computed values.
//!
//! The fixtures are generated by this file rather than committed as binaries,
//! so the inputs stay reviewable in the diff. Run with `UPDATE_GOLDEN=1` to
//! rewrite the snapshots after an intentional behavior change — and read the
//! diff before committing it, because a snapshot that changes silently is the
//! whole failure mode these tests exist to catch.

use engine::io::xlsx;
use engine::{Action, CellAddr, Engine};
use std::path::PathBuf;

fn fixtures_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .unwrap()
        .parent()
        .unwrap()
        .join("fixtures")
}

fn set(e: &mut Engine, sheet: &str, a1: &str, input: &str) {
    e.apply(&Action::CellEdit {
        sheet: sheet.into(),
        addr: CellAddr::parse_a1(a1).unwrap(),
        input: input.into(),
    })
    .unwrap();
}

/// A dues ledger exercising the function families a real back-office sheet
/// leans on: lookup, conditional aggregation, text, and dates.
fn dues_ledger() -> Engine {
    let mut e = Engine::new();
    e.now_ms = 1_704_110_400_000; // 2024-01-01T12:00:00Z, so TODAY() is stable

    e.apply(&Action::SheetRename {
        from: "Sheet1".into(),
        to: "Ledger".into(),
    })
    .unwrap();
    e.apply(&Action::SheetAdd {
        name: "Rates".into(),
    })
    .unwrap();

    // Rate card: membership tier -> annual dues.
    for (i, (tier, rate)) in [("basic", "120"), ("plus", "300"), ("pro", "750")]
        .iter()
        .enumerate()
    {
        let r = i + 1;
        set(&mut e, "Rates", &format!("A{r}"), tier);
        set(&mut e, "Rates", &format!("B{r}"), rate);
    }

    let headers = ["member", "tier", "joined", "paid"];
    for (c, h) in headers.iter().enumerate() {
        set(
            &mut e,
            "Ledger",
            &format!("{}1", (b'A' + c as u8) as char),
            h,
        );
    }
    let rows = [
        ("Ada", "pro", "2021-03-15", "750"),
        ("Grace", "basic", "2022-07-01", "0"),
        ("Alan", "plus", "2020-11-30", "150"),
        ("Katherine", "pro", "2023-01-09", "750"),
        ("Edsger", "basic", "2019-05-22", "120"),
    ];
    for (i, (name, tier, joined, paid)) in rows.iter().enumerate() {
        let r = i + 2;
        set(&mut e, "Ledger", &format!("A{r}"), name);
        set(&mut e, "Ledger", &format!("B{r}"), tier);
        set(&mut e, "Ledger", &format!("C{r}"), joined);
        set(&mut e, "Ledger", &format!("D{r}"), paid);
        // Owed, balance, status, and a display label.
        set(
            &mut e,
            "Ledger",
            &format!("E{r}"),
            &format!("=VLOOKUP(B{r},Rates!A1:B3,2,FALSE)"),
        );
        set(&mut e, "Ledger", &format!("F{r}"), &format!("=E{r}-D{r}"));
        set(
            &mut e,
            "Ledger",
            &format!("G{r}"),
            &format!("=IF(F{r}<=0,\"settled\",IF(F{r}>=E{r},\"unpaid\",\"partial\"))"),
        );
        set(
            &mut e,
            "Ledger",
            &format!("H{r}"),
            &format!("=PROPER(A{r})&\" (\"&UPPER(B{r})&\")\""),
        );
        // DATEVALUE is not in the v1 set, so pull the year out of the ISO
        // text — what a user without it would do.
        set(
            &mut e,
            "Ledger",
            &format!("I{r}"),
            &format!("=VALUE(LEFT(C{r},4))"),
        );
        set(
            &mut e,
            "Ledger",
            &format!("J{r}"),
            &format!("=TEXT(E{r},\"$#,##0.00\")"),
        );
    }

    // Summary block.
    set(&mut e, "Ledger", "A9", "total owed");
    set(&mut e, "Ledger", "B9", "=SUM(E2:E6)");
    set(&mut e, "Ledger", "A10", "total outstanding");
    set(&mut e, "Ledger", "B10", "=SUM(F2:F6)");
    set(&mut e, "Ledger", "A11", "unpaid count");
    set(&mut e, "Ledger", "B11", "=COUNTIF(G2:G6,\"unpaid\")");
    set(&mut e, "Ledger", "A12", "pro dues");
    set(&mut e, "Ledger", "B12", "=SUMIF(B2:B6,\"pro\",E2:E6)");
    set(&mut e, "Ledger", "A13", "average owed");
    set(&mut e, "Ledger", "B13", "=AVERAGE(E2:E6)");
    set(&mut e, "Ledger", "A14", "members joined before 2022");
    set(&mut e, "Ledger", "B14", "=COUNTIF(I2:I6,\"<2022\")");
    set(&mut e, "Ledger", "A15", "longest name");
    set(
        &mut e,
        "Ledger",
        "B15",
        "=MAX(LEN(A2),LEN(A3),LEN(A4),LEN(A5),LEN(A6))",
    );
    // A deliberate error, so the snapshot pins error rendering too.
    set(&mut e, "Ledger", "A16", "missing tier");
    set(
        &mut e,
        "Ledger",
        "B16",
        "=VLOOKUP(\"gold\",Rates!A1:B3,2,FALSE)",
    );

    e
}

/// A formula torture sheet: precedence, coercion, and error propagation.
fn formula_torture() -> Engine {
    let mut e = Engine::new();
    e.now_ms = 1_704_110_400_000;
    let cases = [
        ("A1", "=1+2*3"),
        ("A2", "=(1+2)*3"),
        ("A3", "=2^3^2"),
        ("A4", "=-2^2"),
        ("A5", "=50%*10"),
        ("A6", "=\"a\"&1.5"),
        ("A7", "=1/0"),
        ("A8", "=A7+1"),
        ("A9", "=IFERROR(A7,\"caught\")"),
        ("A10", "=TRUE+1"),
        ("A11", "=\"3\"+4"),
        ("A12", "=Z99+5"),
        ("A13", "=\"x\"&Z99"),
        ("A14", "=0^0"),
        ("A15", "=MOD(-3,2)"),
        ("A16", "=ROUND(2.675,2)"),
        ("A17", "=INT(-1.5)"),
        ("A18", "=SQRT(-1)"),
        ("A19", "=NOSUCHFUNC(1)"),
        ("A20", "=99999<\"a\""),
        ("B1", "=SUM(A1:A6)"),
        ("B2", "=COUNT(A1:A20)"),
        ("B3", "=COUNTA(A1:A20)"),
        ("B4", "=TEXTJOIN(\"|\",TRUE,A1:A5)"),
        ("B5", "=DATE(2024,2,29)"),
        ("B6", "=WEEKDAY(DATE(2024,1,1),2)"),
        ("B7", "=EOMONTH(DATE(2024,1,31),1)"),
        ("B8", "=DATEDIF(DATE(2020,1,1),DATE(2024,3,1),\"M\")"),
    ];
    for (a1, input) in cases {
        set(&mut e, "Sheet1", a1, input);
    }
    e
}

fn check_golden(name: &str, build: fn() -> Engine) {
    let dir = fixtures_dir();
    std::fs::create_dir_all(&dir).expect("create fixtures dir");
    let xlsx_path = dir.join(format!("{name}.xlsx"));
    let snapshot_path = dir.join(format!("{name}.expected.json"));

    let built = build();
    let bytes = xlsx::export(&built.wb).expect("export fixture");
    // The binary is only rewritten on demand: xlsx embeds timestamps, so
    // writing it every run would leave the working tree permanently dirty.
    // The assertions below run against freshly generated bytes regardless,
    // so the committed fixture can never drift from its generator unnoticed.
    let refresh = std::env::var("UPDATE_GOLDEN").is_ok() || !xlsx_path.exists();
    if refresh {
        std::fs::write(&xlsx_path, &bytes).expect("write fixture");
    }

    // The real assertion: importing the file back and recalculating from
    // scratch must reproduce the same computed values.
    let imported = xlsx::import(&bytes).expect("import fixture");
    assert!(
        imported.warnings.is_empty(),
        "{name}: unexpected import warnings: {:?}",
        imported.warnings
    );
    let mut engine = imported.engine;
    engine.now_ms = built.now_ms;
    engine.recalc_all();

    let actual = engine.wb.state_snapshot();
    let pretty = serde_json::to_string_pretty(&actual).unwrap();

    if std::env::var("UPDATE_GOLDEN").is_ok() || !snapshot_path.exists() {
        std::fs::write(&snapshot_path, format!("{pretty}\n")).expect("write snapshot");
        return;
    }

    let expected: serde_json::Value =
        serde_json::from_str(&std::fs::read_to_string(&snapshot_path).expect("read snapshot"))
            .expect("parse snapshot");
    assert_eq!(
        actual, expected,
        "{name}: computed values drifted from the golden snapshot.\n\
         If this change is intentional, rerun with UPDATE_GOLDEN=1 and review the diff."
    );
}

#[test]
fn golden_dues_ledger() {
    check_golden("demo-dues-ledger", dues_ledger);
}

#[test]
fn golden_formula_torture() {
    check_golden("formula-torture", formula_torture);
}

/// Importing a fixture and exporting it again must not change the computed
/// state — the round trip is lossless for everything we model.
#[test]
fn golden_fixtures_round_trip_losslessly() {
    for (name, build) in [
        ("demo-dues-ledger", dues_ledger as fn() -> Engine),
        ("formula-torture", formula_torture as fn() -> Engine),
    ] {
        let built = build();
        let once = xlsx::export(&built.wb).expect("export");
        let mut reimported = xlsx::import(&once).expect("import").engine;
        reimported.now_ms = built.now_ms;
        reimported.recalc_all();
        let twice = xlsx::export(&reimported.wb).expect("re-export");
        let mut again = xlsx::import(&twice).expect("re-import").engine;
        again.now_ms = built.now_ms;
        again.recalc_all();
        assert_eq!(
            reimported.wb.state_snapshot(),
            again.wb.state_snapshot(),
            "{name}: state changed on the second round trip"
        );
    }
}
